random_seed: 0
tie_fwd_bkwd: True
task_ids: [0]
data:
  train_file: molecules_train.json
  valid_file: molecules_valid.json
model:
  name: gqn
  hidden_size: 100
  num_timesteps: 4
  use_graph: True
training:
  epochs: 3000
  patience: 25
  learning_rate: 0.001
  clamp_gradient_norm: 1.0
  out_layer_dropout_keep_prob: 1.0